# Generated by Django 3.2 on 2022-05-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20220519_1526'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(check=models.Q(models.Q(_negated=True, phone__exact=''), models.Q(_negated=True, mobile__exact=''), _connector='OR'), name='must_have_phone_number'),
        ),
    ]
