# Generated by Django 3.2 on 2022-05-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmuser',
            name='is_superuser',
            field=models.BooleanField(
                default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
