# Generated by Django 3.2 on 2022-06-01 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_team_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crmuser',
            options={'verbose_name': 'CRM User', 'verbose_name_plural': 'CRM Users'},
        ),
    ]
